version: '3.8'
services:
  app:
    image: practice_0622
    build: .
    ports:
      - "18080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:25432/practice_0622
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: practice_0622
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "25432:5432"